# Implementing Simple Linear Regression in Python

Numpy: allows operations on single and multi dimensional arrays and
provides access to several mathematical functions.

## 5 steps for simple LR 

1. Import packages and classes needed.
2. Feed in the data (including transformations if necessary).
3. Create the regression model and fit it with the data.
4. Use the results of the model fitting to verify if the it is satisfactory.
5. Make predictions with the model.

In [1]:
# Step 1: Import Packages and Classes
import numpy as np
from sklearn.linear_model import LinearRegression


# Step 2: Feed in the Data
x = np.array([5,15,25,35,45,55]).reshape((-1,1)) #converted into a 2D array
y = np.array([5,20,14,32,22,38])

In [2]:
#we have created two arrays, x (input/independent variable) and y (output/dependent variable).
#function reshape() on x converts the array into two dimensional,
print(x.shape)
print(x)

(6, 1)
[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]


In [3]:
print(y.shape)
print(y)

(6,)
[ 5 20 14 32 22 38]


In [4]:
# Step 3: Create the model and fit the data
model = LinearRegression().fit(x,y)

In [5]:
# Step 4: Results
r_sq = model.score(x,y)
print("Coefficient of determination: ", r_sq)

#the coefficient of determination measures how well a statistical model predicts an outcome.

Coefficient of determination:  0.715875613747954


In [7]:
print("Intercept, θ0: ",model.intercept_)
print("Slope, θ1: ", model.coef_)

Intercept, θ0:  5.633333333333329
Slope, θ1:  [0.54]


In [14]:
# Step 5: Make Prediction
y_pred = model.predict(x)
print('predicted response: ', y_pred, sep='\n')

predicted response: 
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [17]:
#new predictions
x_new = np.array([4, 10, 45, 80]).reshape((-1,1))
y_pred_new = model.predict(x_new)
print('new predicted response: ', y_pred_new, sep='\n')

new predicted response: 
[ 7.79333333 11.03333333 29.93333333 48.83333333]
