# Multi-Layer Perception

Perception is equivalent to a neuron/node in ANN
- It recieves input, which are process by an activation function to produce an output.

There are different types of activation functions:
1. Logistic (Sigmoid) function
2. Trigonometric function (tanh)
3. Rectified Linear Unit function (ReLU) : Default for hidden layers


In [15]:
# Step 1: Import packages and classes

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier

In [16]:
# Step 2: Feed the data

cleveland_df = pd.read_csv('./dataset/processed_cleveland.csv')

# head() outputs the first set of rows.
print(">>>>head<<<<")
print(cleveland_df.head())

# count() returns the number of rows for each column in the dataset.
print(">>>>count<<<<")
print(cleveland_df.count())

# info() provides other additional details, such as the datatype
print(">>>>info<<<<")
print(cleveland_df.info())

>>>>head<<<<
   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

  ca thal  pred_value  
0  0    6           0  
1  3    3           2  
2  2    7           1  
3  0    3           0  
4  0    3           0  
>>>>count<<<<
age           303
sex           303
cp            303
trestbps      303
chol          303
fbs           303
restecg       303
thalach       303
exang         303
oldpeak       303
slope         303
ca            303
thal          303
pred_value    303
dtype: int64
>>>>info<<<<
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0

In [17]:
# Step 3: Remove missing data

cleveland_df["ca"]=pd.to_numeric(cleveland_df["ca"],errors='coerce')
cleveland_df["thal"]=pd.to_numeric(cleveland_df["thal"],errors='coerce')
cleveland_df.dropna(inplace=True)
print(cleveland_df.count())

age           297
sex           297
cp            297
trestbps      297
chol          297
fbs           297
restecg       297
thalach       297
exang         297
oldpeak       297
slope         297
ca            297
thal          297
pred_value    297
dtype: int64


In [18]:
# Step 4: create, train and test

#split the data for train and test
X_train, X_test, y_train, y_test = train_test_split(cleveland_df.drop('pred_value', axis=1), cleveland_df['pred_value'], test_size=0.20, random_state=45)

In [19]:
#normalize(scale) data to allow MLP to converge
scaler = StandardScaler()
scaler.fit(X_train)
#apply transformation to data
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
#create instance of MLP with 2 hidden layers and 3000 iterations
mlp = MLPClassifier(hidden_layer_sizes=(10,10), max_iter=3000)

#overview of parameter values (default)
print(mlp.get_params)

#fit the scaled data
mlp.fit(X_train, y_train)

<bound method BaseEstimator.get_params of MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=3000)>


MLPClassifier(hidden_layer_sizes=(10, 10), max_iter=3000)

In [21]:
# Step 5: Results
#make predictions and generated confusion matrix
pred_result = mlp.predict(X_test)
cm = confusion_matrix(y_test, pred_result)
print(cm)
#generating the classification report
c_report = classification_report(y_test, pred_result)
print(c_report)

[[28  5  0  1  0]
 [ 2  4  0  3  0]
 [ 1  2  1  0  2]
 [ 2  1  1  2  1]
 [ 1  0  1  2  0]]
              precision    recall  f1-score   support

           0       0.82      0.82      0.82        34
           1       0.33      0.44      0.38         9
           2       0.33      0.17      0.22         6
           3       0.25      0.29      0.27         7
           4       0.00      0.00      0.00         4

    accuracy                           0.58        60
   macro avg       0.35      0.34      0.34        60
weighted avg       0.58      0.58      0.58        60

